name: appwrite_auth_kit
description: A wrapper for Appwrite's Accounts service, makes it easy to manage authentication and account features.
version: 0.7.0
homepage: https://github.com/lohanidamodar/appwrite_auth_kit

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  appwrite: ^9.0.0 
  flutter:
    sdk: flutter
    
dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter: null

