name: flappwrite_account_kit
description: A wrapper for Appwrite's Accounts service, makes it easy to use
  Accounts service, manage authentication and account features.
version: 0.0.1
author: Damodar Lohani
homepage: https://github.com/lohanidamodar/flappwrite_account_kit

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
